#!/usr/bin/env php
<?php
$mode = $_SERVER['argv'][1];
$db = $_SERVER['argv'][2];
$user = $_SERVER['argv'][3];
$pass = $_SERVER['argv'][4];

$target = './tests/fixtures/' . $_SERVER['argv'][5] . '/' . (($mode == '--initial') ? 'initial.sql' : 'expected.xml');

if ($mode == '--initial') {
    $test_relevant_tables = array(
        'tl_page',
        'tl_iso_addresses',
        'tl_iso_attributes',
        'tl_iso_baseprice',
        'tl_iso_cart',
        'tl_iso_cart_items',
        'tl_iso_config',
        'tl_iso_downloads',
        'tl_iso_groups',
        'tl_iso_labels',
        'tl_iso_mail',
        'tl_iso_mail_content',
        'tl_iso_order_downloads',
        'tl_iso_order_items',
        'tl_iso_orders',
        'tl_iso_orderstatus',
        'tl_iso_payment_modules',
        'tl_iso_price_tiers',
        'tl_iso_prices',
        'tl_iso_product_categories',
        'tl_iso_productcache',
        'tl_iso_products',
        'tl_iso_producttypes',
        'tl_iso_related_categories',
        'tl_iso_related_products',
        'tl_iso_requestcache',
        'tl_iso_rule_restrictions',
        'tl_iso_rule_usage',
        'tl_iso_rules',
        'tl_iso_shipping_modules',
        'tl_iso_shipping_options',
        'tl_iso_tax_class',
        'tl_iso_tax_rate'
    );
} else {
    $test_relevant_tables = array(
        'tl_page',
        'tl_iso_address',
        'tl_iso_attribute',
        'tl_iso_baseprice',
        'tl_iso_cart',
        'tl_iso_cart_items',
        'tl_iso_config',
        'tl_iso_download',
        'tl_iso_group',
        'tl_iso_label',
        'tl_iso_mail',
        'tl_iso_mail_content',
        'tl_iso_orderstatus',
        'tl_iso_payment',
        'tl_iso_product',
        'tl_iso_product_category',
        'tl_iso_product_collection',
        'tl_iso_product_collection_download',
        'tl_iso_product_collection_item',
        'tl_iso_product_price',
        'tl_iso_product_pricetier',
        'tl_iso_productcache',
        'tl_iso_producttype',
        'tl_iso_related_category',
        'tl_iso_related_product',
        'tl_iso_requestcache',
        'tl_iso_rule_restrictions',
        'tl_iso_rule_usage',
        'tl_iso_rules',
        'tl_iso_shipping',
        'tl_iso_shipping_options',
        'tl_iso_tax_class',
        'tl_iso_tax_rate',
        'tl_nc_gateway',
        'tl_nc_language',
        'tl_nc_message',
        'tl_nc_notification'
    );
}


// allow custom tables
if (count($_SERVER['argv']) > 6) {
   $test_relevant_tables = array_slice($_SERVER['argv'], 6);
}

$tables = implode(' ', $test_relevant_tables);

$xml = ($mode == '--expected') ? ' --xml' : '';

exec("mysqldump$xml --skip-add-locks --order-by-primary $db -u $user -p$pass $tables > $target");