#!/usr/bin/env php
<?php
$db = $_SERVER['argv'][1];
$user = $_SERVER['argv'][2];
$pass = $_SERVER['argv'][3];
$target = $_SERVER['argv'][4];

$test_relevant_tables = array(
    'tl_iso_address',
    'tl_iso_attribute',
    'tl_iso_baseprice',
    'tl_iso_cart',
    'tl_iso_cart_items',
    'tl_iso_config',
    'tl_iso_download',
    'tl_iso_group',
    'tl_iso_label',
    'tl_iso_mail',
    'tl_iso_mail_content',
    'tl_iso_orderstatus',
    'tl_iso_payment',
    'tl_iso_product',
    'tl_iso_product_category',
    'tl_iso_product_collection',
    'tl_iso_product_collection_download',
    'tl_iso_product_collection_item',
    'tl_iso_product_price',
    'tl_iso_product_pricetier',
    'tl_iso_productcache',
    'tl_iso_producttype',
    'tl_iso_related_category',
    'tl_iso_related_product',
    'tl_iso_requestcache',
    'tl_iso_rule_restrictions',
    'tl_iso_rule_usage',
    'tl_iso_rules',
    'tl_iso_shipping',
    'tl_iso_shipping_options',
    'tl_iso_tax_class',
    'tl_iso_tax_rate',
    'tl_nc_gateway',
    'tl_nc_language',
    'tl_nc_message',
    'tl_nc_notification'
);

$tables = implode(' ', $test_relevant_tables);

exec("mysqldump $db --xml --order-by-primary -u $user -p$pass $tables > $target");